#!/bin/zsh
cd /usr/local/src/vim
git=`git pull`
echo $git
if [[ "Already up to date." != $git ]]; then
  old_vim=`vim --version | head -n 2`
  sudo make clean
  ./configure --prefix=/usr/local --with-luajit --enable-channel --enable-cscope --enable-fontset --enable-gpm --enable-icon-cache-update --enable-largefile --enable-multibyte --enable-netbeans --enable-nls --enable-option-checking --enable-terminal --enable-xim --enable-python3interp=yes --enable-pythoninterp=yes --enable-rubyinterp=yes --enable-luainterp=yes && make -j2 && sudo make install
  new_vim=`vim --version | head -n 2`
else
  old_vim="vim is latest version"
fi

cd /usr/local/src/neovim
git=`git pull`
echo $git
if [[ "Already up to date." != $git ]]; then
  old_nvim=`nvim --version | head -n 2`
  sudo rm -rf build && make clean
  make CMAKE_BUILD_TYPE=RelWithDebInfo -j2 && sudo make install
  new_nvim=`nvim --version | head -n 2`
else
  old_nvim="neovim is latest version."
fi

echo $old_vim
echo $new_vim
echo $old_nvim
echo $new_nvim
