#!/bin/zsh
cd /tmp
git clone --depth 1 https://github.com/vim/vim
cd vim
old_vim=`vim --version | head -n 2`
make clean
./configure --prefix=/usr/local --with-luajit --enable-channel --enable-cscope --enable-fontset --enable-gpm --enable-icon-cache-update --enable-largefile --enable-multibyte --enable-netbeans --enable-nls --enable-option-checking --enable-terminal --enable-xim --enable-python3interp=yes --enable-pythoninterp=yes --enable-rubyinterp=yes --enable-luainterp=yes CFLAGS="-O2 -march=armv8-a+crc -pipe" && make -j5 && sudo make install
new_vim=`vim --version | head -n 2`

cd /tmp
git clone --depth 1 https://github.com/neovim/neovim
cd neovim
old_nvim=`nvim --version | head -n 2`
rm -rf build && make clean
make CFLAGS="-O2 -march=armv8-a+crc -pipe" CMAKE_BUILD_TYPE=RelWithDebInfo -j5 && sudo make install
new_nvim=`nvim --version | head -n 2`

echo $old_vim
echo $new_vim
echo $old_nvim
echo $new_nvim
