[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'sudar/vim-arduino-syntax'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'suan/vim-instant-markdown'
