[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'insertCharPre'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#augo_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  let g:deoplete#max_list=1000
  inoremap <expr><tab> pumvisible() ? "\<C-n>":"\<tab>"
'''
on_i = 1


[[plugins]]
repo = 'Shougo/vimshell'

# [[plugins]]
# repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

# [[plugins]]
# repo = 'Shougo/deol.nvim'

# [[plugins]]
# repo = 'Shougo/context_filetype.vim'

# [[plugins]]
# repo = 'thinca/vim-quickrun'
# hook_post_update = '''
#   let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
# '''

# [[plugins]]
# repo = 'kana/vim-repeat'

# [[plugins]]
# repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-scripts/smartchr'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

# [[plugins]]
# repo = 'vim-scripts/taglist.vim'

# [[plugins]]
# repo = 'fatih/vim-go'

# [[plugins]]
# repo = 'sudar/vim-arduino-syntax'

# [[plugins]]
# repo = 'Shougo/deoplete-zsh'

# [[plugins]]
# repo = 'mattn/webapi-vim'

# [[plugins]]
# repo = 'mattn/vim-mastodon'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kurocode25/mdforvim'
