[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'kana/vim-repeat'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/vim-mastodon'

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
