[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'kana/vim-repeat'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/vim-mastodon'

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_source = '''
  let g:EasyMotion_do_mapping = 0
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_source = '''
  let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'skywind3000/asyncrun.vim'

